title: Huy Tran # your name (or website title) here

logo: "/images/mylogonew.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  Work-in-process
  <br><br>
  Learning, Creating, Sharing
  <br><br>
  <a href="https://www.linkedin.com/in/huytran38/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
