title: <p align="center"> Huy Tran </p>

logo: <p align="center"> "/images/mylogonew.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume - Huy T - New2.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/huytran38/">LinkedIn</a> |
  <a href="https://github.com/huytran38">GitHub</a>
  </p>
  
  <p align="justify">
  I am a recent MS Data Science graduate from College of Computing & Digital Media, DePaul University.
  <br><br>
  I am currently a Senior Research Analyst at Ipsos, doing market research work with clients in Hospitality, Automotive and Financial Services.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
