title: Huy Tran </p>

logo: "/images/mylogonew.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume-Huy Tran.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/huytran38/">LinkedIn</a> |
  <a href="https://github.com/huytran38">GitHub</a>
  </p>
  
  <p align="justify">
  I recently completed my Masters in Data Science from College of Computing & Digital Media, DePaul University.
  <br><br>
  I am working as a Senior Research Analyst at Ipsos, doing market research work with clients in 
  Energy, Mobile Communications, and Pharmacy Convenient Stores to assist in understanding their branding and product launches.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
